//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RocksmithFontGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RocksmithFontGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Header {
            get {
                return ResourceManager.GetString("About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect surrogate pair character found at the end of word &quot;{0}&quot;..
        /// </summary>
        public static string Error_AddGlyphs_InvalidSurrogatePair {
            get {
                return ResourceManager.GetString("Error_AddGlyphs_InvalidSurrogatePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This character combination does not fit into 12 bytes: {0}.
        /// </summary>
        public static string Error_AddGlyphs_TooLongCombination {
            get {
                return ResourceManager.GetString("Error_AddGlyphs_TooLongCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured:.
        /// </summary>
        public static string Error_General {
            get {
                return ResourceManager.GetString("Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue anyway? (Height will be resized to {0}).
        /// </summary>
        public static string Error_Generation_GlyphSizeConfirmation {
            get {
                return ResourceManager.GetString("Error_Generation_GlyphSizeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The glyph height for the selected font will be larger than the official fonts (52 pixels)..
        /// </summary>
        public static string Error_Generation_GlyphSizeTooLargeMessage {
            get {
                return ResourceManager.GetString("Error_Generation_GlyphSizeTooLargeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glyph Size Too Large.
        /// </summary>
        public static string Error_Generation_GlyphSizeTooLargeTitle {
            get {
                return ResourceManager.GetString("Error_Generation_GlyphSizeTooLargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one inner bounding rect is larger than the outer..
        /// </summary>
        public static string Error_Generation_OverlappingBoundingRects {
            get {
                return ResourceManager.GetString("Error_Generation_OverlappingBoundingRects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The glyphs did not fit into the max size texture.
        /// </summary>
        public static string Error_Generation_TooManyGlyphs {
            get {
                return ResourceManager.GetString("Error_Generation_TooManyGlyphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading the file failed:.
        /// </summary>
        public static string Error_OpenFile_Failure {
            get {
                return ResourceManager.GetString("Error_OpenFile_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not a valid RS2014 vocals XML file..
        /// </summary>
        public static string Error_OpenFile_WrongFormat {
            get {
                return ResourceManager.GetString("Error_OpenFile_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Error_Warning {
            get {
                return ResourceManager.GetString("Error_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDS File Only.
        /// </summary>
        public static string FileFilter_DDS {
            get {
                return ResourceManager.GetString("FileFilter_DDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File and DDS File.
        /// </summary>
        public static string FileFilter_PNGandDDS {
            get {
                return ResourceManager.GetString("FileFilter_PNGandDDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files.
        /// </summary>
        public static string FileFilter_TXT {
            get {
                return ResourceManager.GetString("FileFilter_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS2014 Vocals XML Files.
        /// </summary>
        public static string FileFilter_XML {
            get {
                return ResourceManager.GetString("FileFilter_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string FontWeight_Black {
            get {
                return ResourceManager.GetString("FontWeight_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string FontWeight_Bold {
            get {
                return ResourceManager.GetString("FontWeight_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string FontWeight_Light {
            get {
                return ResourceManager.GetString("FontWeight_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string FontWeight_Medium {
            get {
                return ResourceManager.GetString("FontWeight_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string FontWeight_Normal {
            get {
                return ResourceManager.GetString("FontWeight_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        public static string UI_Button_Config {
            get {
                return ResourceManager.GetString("UI_Button_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open File....
        /// </summary>
        public static string UI_Button_OpenFile {
            get {
                return ResourceManager.GetString("UI_Button_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string UI_Button_Recalculate {
            get {
                return ResourceManager.GetString("UI_Button_Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets texture size to 512x512 and recalculates the size needed..
        /// </summary>
        public static string UI_Button_Recalculate_Tooltip {
            get {
                return ResourceManager.GetString("UI_Button_Recalculate_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R_eset to Defaults.
        /// </summary>
        public static string UI_Button_ResetDefaults {
            get {
                return ResourceManager.GetString("UI_Button_ResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets all settings to default values..
        /// </summary>
        public static string UI_Button_ResetDefaults_Tooltip {
            get {
                return ResourceManager.GetString("UI_Button_ResetDefaults_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Font....
        /// </summary>
        public static string UI_Button_SaveFont {
            get {
                return ResourceManager.GetString("UI_Button_SaveFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: {0}.
        /// </summary>
        public static string UI_Default_Tooltip {
            get {
                return ResourceManager.GetString("UI_Default_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string UI_Header_Advanced {
            get {
                return ResourceManager.GetString("UI_Header_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string UI_Header_Config {
            get {
                return ResourceManager.GetString("UI_Header_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string UI_Label_CreatedBy {
            get {
                return ResourceManager.GetString("UI_Label_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Shadow.
        /// </summary>
        public static string UI_Label_DropShadowSettings {
            get {
                return ResourceManager.GetString("UI_Label_DropShadowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Font.
        /// </summary>
        public static string UI_Label_FontSettings {
            get {
                return ResourceManager.GetString("UI_Label_FontSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_ize:.
        /// </summary>
        public static string UI_Label_FontSize {
            get {
                return ResourceManager.GetString("UI_Label_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanji/Kana Si_ze:.
        /// </summary>
        public static string UI_Label_FontSizeKanji {
            get {
                return ResourceManager.GetString("UI_Label_FontSizeKanji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Weight:.
        /// </summary>
        public static string UI_Label_FontWeight {
            get {
                return ResourceManager.GetString("UI_Label_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal _Margin:.
        /// </summary>
        public static string UI_Label_HorizontalMargin {
            get {
                return ResourceManager.GetString("UI_Label_HorizontalMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information &amp; Help:.
        /// </summary>
        public static string UI_Label_InfoAndHelp {
            get {
                return ResourceManager.GetString("UI_Label_InfoAndHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string UI_Label_Language {
            get {
                return ResourceManager.GetString("UI_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur:.
        /// </summary>
        public static string UI_Label_ShadowBlur {
            get {
                return ResourceManager.GetString("UI_Label_ShadowBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth:.
        /// </summary>
        public static string UI_Label_ShadowDepth {
            get {
                return ResourceManager.GetString("UI_Label_ShadowDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string UI_Label_ShadowDirection {
            get {
                return ResourceManager.GetString("UI_Label_ShadowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity:.
        /// </summary>
        public static string UI_Label_ShadowOpacity {
            get {
                return ResourceManager.GetString("UI_Label_ShadowOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing A_djustment:.
        /// </summary>
        public static string UI_Label_SpacingAdjustment {
            get {
                return ResourceManager.GetString("UI_Label_SpacingAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reducing this value will reduce the gap between characters..
        /// </summary>
        public static string UI_Label_SpacingAdjustment_Tooltip {
            get {
                return ResourceManager.GetString("UI_Label_SpacingAdjustment_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Size:.
        /// </summary>
        public static string UI_Label_TextureSize {
            get {
                return ResourceManager.GetString("UI_Label_TextureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string UI_Label_Version {
            get {
                return ResourceManager.GetString("UI_Label_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Accurate Inner _Rects.
        /// </summary>
        public static string UI_Option_AccurateInnerRects {
            get {
                return ResourceManager.GetString("UI_Option_AccurateInnerRects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures the inner bounding rects from pixels..
        /// </summary>
        public static string UI_Option_AccurateInnerRects_Tooltip {
            get {
                return ResourceManager.GetString("UI_Option_AccurateInnerRects_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string UI_Option_DarkTheme {
            get {
                return ResourceManager.GetString("UI_Option_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display _Bounding Rectangles.
        /// </summary>
        public static string UI_Option_DisplayBoundingRectangles {
            get {
                return ResourceManager.GetString("UI_Option_DisplayBoundingRectangles", resourceCulture);
            }
        }
    }
}
